# Generated by Django 3.1.3 on 2020-11-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartloop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='timezone',
        ),
    ]
